# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godo < Formula
  desc ""
  homepage "https://github.com/ritikdhasmana/godo"
  version "0.1.0"

  on_macos do
    url "https://github.com/ritikdhasmana/godo/releases/download/v0.1.0/godo_Darwin_all.tar.gz"
    sha256 "0e3da712c13d85f0b7dd5bf3cb3bdc40e5f43c895a36462c3cd98e1a6882009e"

    def install
      bin.install "godo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ritikdhasmana/godo/releases/download/v0.1.0/godo_Linux_arm64.tar.gz"
      sha256 "85afaebb957c0c465ff7e3d5943f3b4042f1f4a87c72b42da451446bd44e0ee7"

      def install
        bin.install "godo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ritikdhasmana/godo/releases/download/v0.1.0/godo_Linux_x86_64.tar.gz"
      sha256 "21342ea4838703e92975377e88b5cc78204eb315c9d92fc72114f2118b133a10"

      def install
        bin.install "godo"
      end
    end
  end
end
