# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godo < Formula
  desc ""
  homepage "https://github.com/ritikdhasmana/godo"
  version "0.3.0"

  on_macos do
    url "https://github.com/ritikdhasmana/godo/releases/download/v0.3.0/godo_Darwin_all.tar.gz"
    sha256 "9b290301bf820240653a1168669eafc7da4d14e29a498ed2d6daf75da8925626"

    def install
      bin.install "godo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ritikdhasmana/godo/releases/download/v0.3.0/godo_Linux_arm64.tar.gz"
      sha256 "ff28327c99ed38900e45b484e82046152689fe4313346d9986f42abc9eae3ff4"

      def install
        bin.install "godo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ritikdhasmana/godo/releases/download/v0.3.0/godo_Linux_x86_64.tar.gz"
      sha256 "cbe1e66fa682b7af631e15b50d6f6a2049039a3523f1305fa8127cd69c88914e"

      def install
        bin.install "godo"
      end
    end
  end
end
